name: 'Java SDK code checks'

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-java/**'
            - '.github/workflows/java-sdk.yml'
    merge_group:

jobs:
    build:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set BUILD_VERSION
              run: echo "BUILD_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-b$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build
              run: |
                  cd /sdk/highlight-java
                  mvn clean package --batch-mode -DskipTests -Drevision=$BUILD_VERSION
                  mv  highlight-sdk/targat/highlight-sdk-*.jar ./
                  mv  highlight-log-*/targat/highlight-log-*.jar ./

            - name: Publish build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: highlight-java-sdk
                  path: /sdk/highlight-java/highlight-sdk-*.jar

            - name: Test
              run: |
                  cd /sdk/highlight-java
                  mvn clean test --batch-mode -Dmaven.test.failure.ignore=true -Drevision=$BUILD_VERSION

            - name: Publish test report
              uses: mikepenz/action-junit-report@v3
              if: always()
              with:
                  name: junit-test-results
                  path: '/sdk/highlight-java/**/target/surefire-reports/*.xml'
                  retention-days: 1